### ISSUE TITLE
Sound ausgabe

### ISSUE THREAD

**Issue by thimmy687** [serlo-org/serlo-abc#111]
Hallo Leute,

kann es sein das bei eurem Prototypen die Soundausgabe noch nicht funktioniert?

(der [web prototyp](https://abc.serlo.org/try/#3) )

**Comment by elbotho** [comment]
Hi, 
in unserer legacy Version gibt es eine Soundausgabe, die aber auf verschiedenen Geräten Probleme macht. Am besten sollte es mit Chrome/Chromium laufen.

**Comment by inyono** [comment]
Closed because not relevant to the react native app. If you want to fix that, @elbotho, you can create the issue in abc-legacy.
