### ISSUE TITLE
Backlog erster Sprint

### ISSUE THREAD

**Issue by ronnitatserlo** [serlo-org/serlo-abc#2]
- [ ] Audios abspielen
- [ ] Videos abspielen
- [ ] Auf dem Bildschirm zeichnen
- [ ] Audio controls / Multimedia controls 
- [ ] Audio recording
- [ ] Offlineverfügbarkeit (git vs http)
- [ ] Update fetching
- [ ] Animation (gifs / svg)
- [ ] Styles vergleichen
- [ ] Gestenerkennung
- [ ] Trace check
- [ ] Vibration

**Comment by inyono** [comment]
no longer relevant
