### ISSUE TITLE
exercise: "Schreiben Sie den Buchstaben"

### ISSUE THREAD

**Issue by thellmund** [serlo-org/serlo-abc#24]

**Comment by zepatrik** [comment]
![bildschirmfoto 2017-02-16 um 10 17 55](https://cloud.githubusercontent.com/assets/5354445/25481380/31322944-2b4d-11e7-84a0-0e42057ed459.png)
Should it create some kind of trace object? Or should the user just be able to draw something?

**Comment by zepatrik** [comment]
There is another app we could copy the concept of. [Here](https://youtu.be/RhjUHt2oPBE) is a demo video. Seems like there are predefined lines you have to hit. It will show an arrow when its out of that line. They use points to repeat learned symbols. Might be an inspiration @ronnitatserlo

**Comment by inyono** [comment]
for now: only draw

**Comment by igorzamyslov** [comment]
Hey @inyono,
We have some progress with this exercise, could you please check [this branch](https://github.com/cognostics/serlo-abc/tree/letter_sketch_example), there is a new story in Storybook (Letter Sketch), which shows an example of how it can work.

The problem with the example that it works too slow on Android. I might have an idea how to fix it, but there are some issues with that - you can briefly read about it in the comments of the component itself, it is located at `src/components/LetterSketchExample.js`.

It would be nice if you could give some feedback about this example :)

P.S. I hope by the end of tomorrow I will have something to show for this exercise: https://github.com/serlo-org/serlo-abc/issues/56
