### ISSUE TITLE
Wrong Text / Image

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/serlo-abc#273]
EU Wörter hören: zu Bild Werkzeug wird "ankreuzen" gesprochen
C Wörter hören: Cafe hat falsches Bild (Getränk statt Ort) und wird nicht vorgesprochen, fortsetzen nicht möglich

**Comment by Knorrke** [comment]
Werkzeug has wrong sound file

**Comment by Mariiiam** [comment]
Cafe has wrong image
