### ISSUE TITLE
missing input option

### ISSUE THREAD

**Issue by Mariiiam** [serlo-org/serlo-abc#274]
EU	fehlende Buchstaben ergänzen	zu BAUM fehlt Eingabemöglichkeit
X	fehlende Buchstaben ergänzen	zu ROSE, TEXT, MAUS, TAXI, ZUG fehlt EIngabemöglichkeit
Ei	Buchstabe fehlt	zu EI keine Eingabemöglichkeit
Ü	Buchstabe fehlt	zu KUH keine Eingabemöglichkeit
V	Buchstabe ergänzen	zu ARM und SEE fehlt EIngabemöglichkeit
ß	Buchstabe ergänzen	zu BUS fehlt EIngabemöglichkeit
J	Buchstabe ergänzen	zu JA fehlt EIngabemöglichkeit

**Comment by Knorrke** [comment]
This happens because the height of the buttons is 0, when there is no text around it. So adding `min-width:'30px'` (or maybe bigger, try with one of the failing cases above to see what looks right) to the button style should probably work.

**Comment by Mariiiam** [comment]
Problem doesn't appear when the number of missing letters is smaller than the number of letters in the word.
