### ISSUE TITLE
back to menu

### ISSUE THREAD

**Issue by Mariiiam** [serlo-org/serlo-abc#277]
Ö, QU	Menüpunkt Buchstabe	statt Bilder Vorentlastung kommt Startbildschirm Serlo
Ä	Wörter hören	nach Käfig kommt Startbildschirm Serlo
U	Wörter hören	nach Fluss kommt Startbildschirm Serlo

**Comment by Knorrke** [comment]
[ ] - `"words": ["föhn", "löffel", "knödel"]` should be `"words":["foehn", "loeffel", "knoedel"]`
[ ] - `IntroduceLetter` expects three words, but QU only has two new words.
[ ] - Kaefer is missing in `packages\assets\words.json`
[ ] - `schuh` should be `schuhe` in `packages\assets\course.json`
