### ISSUE TITLE
Video not shown in full-length for letters "Eu X Ö"

### ISSUE THREAD

**Issue by ChristineOmeltschenko** [serlo-org/serlo-abc#322]
First part of video 13 is missing for letters "Eu X Ö". Video isn't shown in full-length.

Please exchange video and insert video 13 in full-length instead. (Video normally starts with the view INSIDE the fridge; audience has a look inside the fridge)

Probably issue is only seen on smartphones?

**Comment by gesine57** [comment]
Fehlerfassung - Nachfolger ist Issue #354
