### ISSUE TITLE
Letter Z: no correct end

### ISSUE THREAD

**Issue by gesine57** [serlo-org/serlo-abc#324]
Am Ende fehlt das Lobvideo, stattdessen kommt bei Weiter das Startmenü und der Buchstabe ist nicht als an- bzw. abgearbeitet markiert

**Comment by Knorrke** [comment]
This works in my local version, can you check that again @gesine57? Also: the Write-Letter exercise doesn't display the uppercase Z on my device, can you confirm that in the development version?

**Comment by Knorrke** [comment]
Thanks for testing :)
