### ISSUE TITLE
Video 11 not shown in full-length for letters "J NG Ü"

### ISSUE THREAD

**Issue by ChristineOmeltschenko** [serlo-org/serlo-abc#325]
Only first half of video 11(topic:"Briefmarke leihen von Nena) is shown for letters "J NG Ü".

Please insert video 11(topic:"Briefmarke leihen von Nena) in full-length for letters "J NG Ü"

**Comment by gesine57** [comment]
Fehlerfassung - Nachfolger ist Issue #354
