### ISSUE TITLE
Letter Qu without sound

### ISSUE THREAD

**Issue by gesine57** [serlo-org/serlo-abc#348]
Nach den Bildern fehlt zu Buchstabe Qu die Audiodatei, Serlo bleibt hängen.

**Comment by inyono** [comment]
The reason for that is probably that we don't have a `qu.mp3` sound file, but rather a couple of variations (`q.mp3`, `quu.mp3`, `quue.mp3`). Needs to be handled here: https://github.com/serlo-org/serlo-abc/blob/4828f653634000ec25fd93e86f10945306b5bf57/packages/entities/exercise-groups/present-letter.ts#L21 (among other occurrences). You can probably search for `sound` in the exercise groups to find all places where we might load letter sounds. Alternatively: rename the preferred sound to `qu.mp3`.

**Comment by Knorrke** [comment]
As discussed with @gesine57 : We should use `q.mp3` here
