### ISSUE TITLE
Repeat letter / word

### ISSUE THREAD

**Issue by gesine57** [serlo-org/serlo-abc#359]
Nach Abspielen der Aufnahme nochmal Original abspielen

**Comment by stehrenberg** [comment]
Nachdem die Aufnahme vong Nutzer*in her noch einmal abgespielt wurde:
Sollen dann *beide* Beispiellaute ("Normal"-form UND Langform) der Wörter und Buchstaben nach der Nutzer*in-Aufnahme noch einmal abgespielt werden?
Oder wollt ihr da nur eine der beiden Formen?

Implementiert ist vorerst "beide Formen".
