### ISSUE TITLE
exercise: "Ordnen Sie den Artikel zu"

### ISSUE THREAD

**Issue by ronnitatserlo** [serlo-org/serlo-abc#55]
![04](https://cloud.githubusercontent.com/assets/20284270/24862644/ae9d5956-1dfd-11e7-974a-8978c3245985.jpg)

**Comment by zepatrik** [comment]
Selected:
![tmp_9912-screenshot_20170420-203830447458640](https://cloud.githubusercontent.com/assets/5354445/25247096/22330802-260a-11e7-97f4-24c02058be46.png)
Not selected
![tmp_9912-screenshot_20170420-2038001709196948](https://cloud.githubusercontent.com/assets/5354445/25247146/4939562c-260a-11e7-8ae7-ec82ede567ef.png)

**Comment by inyono** [comment]
I would swap the opacity for selected and unselected. The selected one should be highlighted more, IMHO. Other than that, it looks pretty nice 👍

**Comment by zepatrik** [comment]
The selected colors are the ones form the screenshot on the very top and the others just with less saturation. Should those be in the colors.js?
We might need them at some point again.

**Comment by inyono** [comment]
Yeah, please add them to `colors.js` :)
