### ISSUE TITLE
assets: videos

### ISSUE THREAD

**Issue by inyono** [serlo-org/serlo-abc#89]
Add videos in "just good enough" quality (see #88 for long-term plans)

**Comment by ronnitatserlo** [comment]
There is one more adjustment that's being made to the large video files, I will upload it on Monday (or so I hope). For the snippets I have to check and will get back to you.

**Comment by inyono** [comment]
Thanks :)

**Comment by ronnitatserlo** [comment]
The snippets are here: https://drive.google.com/drive/folders/0B-onL87d589pWkZxY29uV2pkN2s?usp=sharing

**Comment by inyono** [comment]
superseded by #173
