### ISSUE TITLE
feature: enqueue wrongly solved exercises

### ISSUE THREAD

**Issue by inyono** [serlo-org/serlo-abc#93]
@ronnitatserlo  @andreas-serlo 
In the prototype, wrongly solved exercises will be assigned again at the end of the chapter. Is this also the intended behavior for the real app?

**Comment by ronnitatserlo** [comment]
No, in the real app wrongly solved exercises should be shown again immediately after and also repeated at the end of the chapter. This is to help learners to understand an exercise by trial and error.

**Comment by inyono** [comment]
Okay, to summarize:
* When the user submits a wrong solution, the negative feedback sound is played and the same exercise (with the exact same words/letters) is assigned again without showing the correct solution first (?)
* At the end of the chapter, the exercise is also assigned again (with the exact same words/letters (?))
